# Copyright 2020, 2021, 2022 Clément "carlodrift" Raynaud and contributors
#
# This file is part of TabCompleterManager.
#
# TabCompleterManager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TabCompleterManager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with TabCompleterManager.  If not, see <https://www.gnu.org/licenses/>.

name: TabCompleterManager
version: ${project.version}
main: net.clementraynaud.tabcompletermanager.TabCompleterManager
api-version: 1.13
authors: [ carlodrift ]
description: Simple Tab Completer Manager
website: ${project.url}
commands:
  tcm:
    description: The command to use TabCompleterManager.
    usage: /tcm
